#!/usr/bin/env python3
"""Design the 48 kHz -> 24 kHz input decimator.

The current decimator averages two adjacent samples. As an anti-alias filter
that is close to useless: it is -1.25 dB at 8 kHz (audible dulling of the
reverb input) and only -6 dB at 16 kHz, so anything up there folds straight
back down onto 8 kHz almost unattenuated.

A half-band FIR fixes both. Half-band means every other tap is exactly zero and
the centre tap is exactly 0.5, so a filter with P nonzero pairs costs only P
multiplies per output sample - and this runs in the 48 kHz ISR, so cost is the
binding constraint.

Half-band responses are antisymmetric about fs/4 (12 kHz here), so passband
edge and stopband edge are mirrored: pushing the passband up to 10 kHz forces
the stopband to start at 14 kHz. Content between 12 and 14 kHz still aliases;
everything above 14 kHz is killed.
"""
import numpy as np

FS = 48000.0


def halfband(pairs, beta):
    """Kaiser-windowed half-band. Taps at +-1, +-3, ... +-(2*pairs-1)."""
    n = np.arange(-(2*pairs - 1), 2*pairs)
    h = 0.5 * np.sinc(n / 2.0)
    N = len(n)
    w = np.kaiser(N, beta)
    h = h * w
    # force exact half-band structure
    h[np.abs(n) % 2 == 0] = 0.0
    h[n == 0] = 0.5
    # normalise to unity DC
    h = h / h.sum()
    return n, h


def response(h, n, freqs):
    out = []
    for f in freqs:
        w = 2 * np.pi * f / FS
        out.append(abs(np.sum(h * np.exp(-1j * w * n))))
    return np.array(out)


print("Passband loss (dB) and worst alias leakage\n")
print("  design            2k     4k     6k     8k    10k |  worst stop >14k | mults/out")
print("  " + "-" * 78)

# current boxcar, for reference
nb = np.array([0, 1])
hb = np.array([0.5, 0.5])
pb = response(hb, nb, [2000, 4000, 6000, 8000, 10000])
stop = response(hb, nb, np.linspace(14000, 24000, 200))
print(f"  boxcar (current) " + "".join(f"{20*np.log10(v):7.2f}" for v in pb) +
      f" | {20*np.log10(stop.max()):9.1f} dB    |    1")

STOP_EDGE = 14000.0     # protects the audible band up to 10 kHz after folding
PB_LIMIT_DB = -0.15     # allowed loss at 8 kHz

best = None
for pairs in range(2, 15):
    # pick the window that buys the most stopband rejection while keeping the
    # passband essentially flat where it matters
    cand = None
    for beta in np.arange(2.0, 14.01, 0.25):
        n, h = halfband(pairs, beta)
        pb = response(h, n, [2000, 4000, 6000, 8000, 10000])
        if 20*np.log10(pb[3]) < PB_LIMIT_DB:
            continue
        stop = response(h, n, np.linspace(STOP_EDGE, 24000, 400))
        sdb = 20*np.log10(stop.max())
        if cand is None or sdb < cand[0]:
            cand = (sdb, beta, n, h, pb)
    if cand is None:
        continue
    sdb, beta, n, h, pb = cand
    print(f"  halfband P={pairs:<2d}    " + "".join(f"{20*np.log10(v):7.2f}" for v in pb) +
          f" | {sdb:9.1f} dB    |    {pairs}   (beta {beta:.2f})")
    if best is None and sdb < -60.0:
        best = (pairs, beta, n, h)

if best is None:
    raise SystemExit("no design met the stopband target")

pairs, beta, n, h = best
print(f"\nChosen: P={pairs} pairs, Kaiser beta={beta}, {len(n)} taps "
      f"({pairs} multiplies per output sample)\n")

# Emit Q15 fixed point: the ISR runs at 48 kHz and should not pull in the FPU
# for this. Centre tap is exactly 0.5 so it stays a shift.
nz = [(int(i), float(v)) for i, v in zip(n, h) if v != 0.0 and i != 0]
print("/* generated by test/design_decimator.py */")
print(f"#define DECIM_PAIRS {pairs}")
q = []
for i, v in nz:
    if i > 0:
        q.append((i, int(round(v * 32768.0))))
print("static const int32_t decim_q15[DECIM_PAIRS] = {",
      ", ".join(str(c) for _, c in q), "};")
print("/* taps at offsets", ", ".join(str(i) for i, _ in q), "each paired with its mirror;")
print("   centre tap is exactly 0.5 -> a shift, not a multiply */")

# verify the quantised version still behaves
hq = h.copy()
for idx, (i, c) in enumerate(zip([i for i, _ in q], [c for _, c in q])):
    pass
hq = np.zeros_like(h)
for k, i in enumerate(n):
    if i == 0:
        hq[k] = 0.5
    elif i % 2 != 0:
        c = int(round(h[k] * 32768.0))
        hq[k] = c / 32768.0
gain = hq.sum()
pbq = response(hq, n, [2000, 4000, 6000, 8000, 10000]) / gain
stopq = response(hq, n, np.linspace(14000, 24000, 400)) / gain
print(f"\nafter Q15 quantisation: 8 kHz {20*np.log10(pbq[3]):+.2f} dB, "
      f"worst alias {20*np.log10(stopq.max()):.1f} dB, dc gain {gain:.6f}")
