#!/usr/bin/env python3
"""Emit the 6-point 5th-order Lagrange interpolator in Horner form.

Derived with exact rational arithmetic rather than written out by hand: a
single wrong sign here is a filter with gain slightly above unity, which in a
0.999-feedback loop is not a subtle artefact but a runaway.

Nodes sit at -2,-1,0,1,2,3 relative to the sample below the read position, so
y[2] is the sample at f == 0 and the result must reduce to exactly y[2] there.
"""
from fractions import Fraction as F

NODES = [-2, -1, 0, 1, 2, 3]
N = len(NODES)


def poly_mul(a, b):
    out = [F(0)] * (len(a) + len(b) - 1)
    for i, ai in enumerate(a):
        for j, bj in enumerate(b):
            out[i + j] += ai * bj
    return out


# w[k] as a degree-5 polynomial in f
weights = []
for k in range(N):
    p = [F(1)]
    for j in range(N):
        if j == k:
            continue
        # (f - x_j) / (x_k - x_j)
        denom = F(NODES[k] - NODES[j])
        p = poly_mul(p, [F(-NODES[j]) / denom, F(1) / denom])
    weights.append(p)

# c[m] = sum_k coeff_of_f^m_in_w[k] * y[k]
print("/* generated by test/gen_lagrange6.py -- do not edit by hand */")
for m in range(6):
    terms = []
    for k in range(N):
        c = weights[k][m]
        if c == 0:
            continue
        terms.append((c, k))
    expr = []
    for c, k in terms:
        if c.denominator == 1:
            lit = f"{c.numerator}.0f"
        else:
            lit = f"({c.numerator}.0f / {c.denominator}.0f)"
        expr.append(f"{lit} * y{k}")
    print(f"float c{m} = " + " + ".join(expr) + ";")

print("\nreturn ((((c5 * f + c4) * f + c3) * f + c2) * f + c1) * f + c0;")

# sanity: at f == 0 the result must be exactly y2, and the weights must sum to
# 1 at every f (unity DC gain, the property that keeps peak gain at 1.0).
assert [w[0] for w in weights] == [F(0), F(0), F(1), F(0), F(0), F(0)], "f=0 must give y2"
for m in range(6):
    s = sum(weights[k][m] for k in range(N))
    assert s == (F(1) if m == 0 else F(0)), f"weights must sum to 1 at power {m}"
print("\n/* verified: exact passthrough at f==0, weights sum to 1 for all f */")
